
development:
  adapter: postgresql
  database: InvestorCaps_development
  username: postgres
  password: password
  host: localhost
  encoding: UTF8 

test: &test
  adapter: postgresql
  database: InvestorCaps_test
  username: postgres
  password: password
  host: localhost
  encoding: UTF8 

production:
  adapter: postgresql
  database: InvestorCaps_production
  username: postgres
  password: password
  host: localhost
  encoding: UTF8 

cucumber:
  <<: *test